language: php
php: 7.1
before_install:
  - composer self-update
cache:
  directories: $HOME/.composer/cache
before_script:
  - composer install --no-interaction --dev --working-dir=code
script:
  - php code/vendor/bin/phpunit --configuration=code/phpunit.xml --coverage-clover=coverage.xml
after_success: bash <(curl -s https://codecov.io/bash)